# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\College and Courses\College\Operating systems\Practical\ManualEntry.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ManualEntryWidnow(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(220, 240)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 220, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.CurrentProcessLabel = QtWidgets.QLabel(Form)
        self.CurrentProcessLabel.setGeometry(QtCore.QRect(160, 10, 60, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setPointSize(14)
        self.CurrentProcessLabel.setFont(font)
        self.CurrentProcessLabel.setText("")
        self.CurrentProcessLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.CurrentProcessLabel.setObjectName("CurrentProcessLabel")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 100, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.ArrivalTimeSpin = QtWidgets.QSpinBox(Form)
        self.ArrivalTimeSpin.setGeometry(QtCore.QRect(160, 80, 50, 20))
        self.ArrivalTimeSpin.setObjectName("ArrivalTimeSpin")
        self.BurstTimeSpin = QtWidgets.QSpinBox(Form)
        self.BurstTimeSpin.setGeometry(QtCore.QRect(160, 120, 50, 20))
        self.BurstTimeSpin.setObjectName("BurstTimeSpin")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 110, 100, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.PrioSpin = QtWidgets.QSpinBox(Form)
        self.PrioSpin.setGeometry(QtCore.QRect(160, 160, 50, 20))
        self.PrioSpin.setObjectName("PrioSpin")
        
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(10, 150, 100, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.PrevButton = QtWidgets.QPushButton(Form)
        self.PrevButton.setGeometry(QtCore.QRect(10, 200, 80, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.PrevButton.setFont(font)
        self.PrevButton.setObjectName("PrevButton")
        self.NextButton = QtWidgets.QPushButton(Form)
        self.NextButton.setGeometry(QtCore.QRect(130, 200, 80, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.NextButton.setFont(font)
        self.NextButton.setObjectName("NextButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Current process:"))
        self.label_4.setText(_translate("Form", "Arrival time"))
        self.label_5.setText(_translate("Form", "Burst time"))
        self.label_6.setText(_translate("Form", "Priority"))
        self.PrevButton.setToolTip(_translate("Form", "Generates the specified number of processes with random arrival times, burst times and priorities"))
        self.PrevButton.setText(_translate("Form", "Previous"))
        self.NextButton.setToolTip(_translate("Form", "Generates the specified number of processes with random arrival times, burst times and priorities"))
        self.NextButton.setText(_translate("Form", "Next"))
