# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\College and Courses\College\Operating systems\SimulationWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SimulationWidget(object):
    def setupUi(self, SimulationWidget):
        SimulationWidget.setObjectName("SimulationWidget")
        SimulationWidget.resize(600, 200)

        self.retranslateUi(SimulationWidget)
        QtCore.QMetaObject.connectSlotsByName(SimulationWidget)

    def retranslateUi(self, SimulationWidget):
        _translate = QtCore.QCoreApplication.translate
        SimulationWidget.setWindowTitle(_translate("SimulationWidget", "Form"))
